sudo: false
language: python
env:
  - DJANGO=1.8
  - DJANGO=1.9
  - DJANGO=1.10a1
python:
  - 2.7
  - 3.4
script: python setup.py test
notifications:
  email:
    - jussi.vaihia@futurice.com
install:
  - pip install Django==$DJANGO --use-mirrors
  - pip install six cachetools django_extensions
